export const TYPE_GROUPS = {
  'Accessories':       ['Accessories'],
  'Clothing':          ['Clothing', 'clothing'],
  'Drivers':           ['Driver', 'driver', 'DRIVER', 'Drivers'],
  'Driver Shafts':     ['Driver Shaft', 'Driver shaft'],
  'Fairway Shafts':    ['Fairway Shaft', 'Fairway shaft'],
  'Fairway Woods':     ['Fairway Wood', 'Fairway wood'],
  'Gift Cards':        ['Gift Cards'],
  'Golf Bags':         ['Golf Bags', 'Golf bags'],
  'Golf Balls':        ['Golf Balls', 'Golf balls'],
  'Golf Club Grips':   ['Golf Club Grips', 'Golf club grips'],
  'Golf Gloves':       ['Golf glove', 'Golf Gloves', 'Golf gloves'],
  'Golf Tees':         ['Golf tees'],
  'Golf Towels':       ['Golf towels'],
  'Golf Training Aids':['Golf training aids'],
  'Golf Trolleys':     ['Golf trolley'],
  'GPS / Rangefinder': ['GPS / Rangefinder', 'Gps / rangefinder'],
  'Headcovers':        ['Headcover'],
  'Hybrids':           ['HYBRID', 'Hybrid', 'hybrid'],
  'Hybrid Shafts':     ['Hybrid Shaft', 'Hybrid shaft'],
  'Individual Irons':  ['Individual Iron', 'Individual iron'],
  'Iron Shafts':       ['Iron Shafts', 'Iron shafts'],
  'Irons':             ['Irons', 'irons'],
  'Job Lot':           ['Job Lot'],
  'Launch Monitor':    ['Launch Monitor', 'Launch monitor'],
  'Package Sets':      ['Package Set', 'Package set'],
  'Putters':           ['Putter', 'Putters'],
  'Putter Shafts':     ['Putter shafts'],
  'Repair Charges':    ['Repair charges'],
  'Shoes':             ['Shoes'],
  'Umbrellas':         ['Umbrella'],
  'Wedges':            ['Wedge', 'wedge'],
  'Wedge Shafts':      ['Wedge shafts'],
  'Wood Sets':         ['Wood Set'],
}
