export const VENDOR_GROUPS = {
  'Accra':               ['Accra'],
  'Adams':               ['Adams'],
  'Aldila':              ['Aldila'],
  'Benross':             ['Benross'],
  'Callaway':            ['Callaway'],
  'Clearance':           ['Clearance'],
  'Cleveland':           ['Cleveland'],
  'Cobra':               ['Cobra'],
  'Fujikura':            ['Fujikura'],
  'GolfClubs4Cash':      ['golfclubs4cash', 'GolfClubs4Cash'],
  'Graphite Design':     ['Graphite design', 'Graphite Design'],
  'Honma':               ['Honma'],
  'KBS':                 ['Kbs', 'KBS'],
  'Kirkland':            ['Kirkland'],
  'Lynx':                ['Lynx'],
  'Mitsubishi Chemical': ['Mitsubishi chemical', 'Mitsubishi Chemical'],
  'Mizuno':              ['Mizuno'],
  'Nike':                ['Nike'],
  'Odyssey':             ['Odyssey'],
  'Ping':                ['Ping'],
  'Project X':           ['Project x', 'Project X'],
  'PXG':                 ['Pxg', 'PXG'],
  'Scotty Cameron':      ['Scotty cameron', 'Scotty Cameron'],
  'Srixon':              ['Srixon'],
  'TaylorMade':          ['Taylormade', 'TaylorMade'],
  'Titleist':            ['Titleist'],
  'UST Mamiya':          ['Ust mamiya', 'UST Mamiya'],
  'Wilson':              ['Wilson'],
  'Wilson Staff':        ['Wilson Staff'],
  'XXIO':                ['XXIO', 'Xxio'],
  'Yes!':                ['Yes!'],
  'Yonex':               ['Yonex'],
}
